# run deploy only when pushing new tags
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-jdk8-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-jdk8
            
      - name: Create Artifacts
        run: ./gradlew assemble
        # just to ensure it compiles; if it doesn't then don't continue

      - name: Configure Signing Key
        run: |
          echo signingKey=$SIGNING_KEY >> gradle.properties
          echo signingPassword=$SIGNING_PASSWORD >> gradle.properties
          echo ossrhUsername=$MAVEN_USERNAME >> gradle.properties
          echo ossrhPassword=$MAVEN_PASSWORD >> gradle.properties

        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}


      - name: Publish package
        run: ./gradlew publish